// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcwgogpzihsailxfoanq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjd2dvZ3B6aWhzYWlseGZvYW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjYxNzMsImV4cCI6MjA2OTI0MjE3M30.0YpMPwlQ5UQsQ3lirF_Y_lyzQLNHcaEixW2lXITMYsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});